[package]
name = "data-structures-and-algorithms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]

name = "array"
path = "concepts/array/main.rs"

